const IMAGE = {
  left: require('../../images/left.png'),
  leftWhite: require('../../images/left-white.png'),
  'left-white': require('../../images/left-white.png'),
  up: require('../../images/up.png'),
  down: require('../../images/down.png'),
  right: require('../../images/right.png'),
  scan: require('../../images/scan.png'),
  female: require('../../images/female.png'),
  male: require('../../images/male.png'),
  card: require('../../images/card.png'),
  message: require('../../images/message.png'),
  remove: require('../../images/remove.png'),
  clean: require('../../images/clean.png'),
  close: require('../../images/close.png'),
  more: require('../../images/more.png'),
  copy: require('../../images/copy.png'),
  'more-c': require('../../images/more-c.png'),
  search: require('../../images/search.png'),
  location: require('../../images/location.png'),
  'location-small': require('../../images/location-small.png'),
  selected: require('../../images/selected.png'),
  emoji: require('../../images/emoji.png'),
  share: require('../../images/share.png'),
  'share-white': require('../../images/share-white.png'),
  bookmark: require('../../images/bookmark.png'),
  'social-moments': require('../../images/social-moments.png'),
  'social-moments-c': require('../../images/social-moments-c.png'),
  'social-wechat': require('../../images/social-wechat.png'),
  'social-wechat-c': require('../../images/social-wechat-c.png'),
  'social-qq': require('../../images/social-qq.png'),
  'social-alipay': require('../../images/social-alipay.png'),
  'social-weibo': require('../../images/social-weibo.png'),
  'social-wechat-s': require('../../images/social-wechat-s.png'),
  'phone': require('../../images/phone.png'),
  can : require('../../images/can.png'),
  pencil: require('../../images/pencil.png'),
  'location-white-small': require('../../images/location-white-small.png'),
  cart: require('../../images/cart.png'),
  'cart_red': require('../../images/cart_sel.png'),
};

export default IMAGE;
